<Project>
  <ItemGroup>
    <PackageVersion Include="Autofac" Version="9.3.0" />
    <PackageVersion Include="Autofac.Extensions.DependencyInjection" Version="11.0.1" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
    <PackageVersion Include="GitVersion.MsBuild" Version="6.8.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageVersion>
    <PackageVersion Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageVersion Include="Mutagen.Bethesda" Version="0.55.0-alpha.48" />
    <PackageVersion Include="Mutagen.Bethesda.Autofac" Version="0.55.0-alpha.48" />
    <PackageVersion Include="Mutagen.Bethesda.Core" Version="0.55.0-alpha.48" />
    <PackageVersion Include="Mutagen.Bethesda.FormKeys.SkyrimSE" Version="3.4.0" />
    <PackageVersion Include="Mutagen.Bethesda.Skyrim" Version="0.55.0-alpha.48" />
    <PackageVersion Include="Mutagen.Bethesda.Testing" Version="0.55.0-alpha.48" />
    <PackageVersion Include="Nifly" Version="1.0.0" />
    <PackageVersion Include="Octokit.GraphQL" Version="0.4.0-beta" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.assert" Version="2.9.0" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageVersion>
  </ItemGroup>
</Project>